name: rebuilder
description: A simple flutter widget to handle your APIs
version: 1.0.0
homepage:

environment:
  sdk: '>=3.0.3 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  dio: ^5.2.1+1
  flutter:
    sdk: flutter
  freezed: ^2.3.5
  freezed_annotation: ^2.2.0
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.5

flutter:
